version: 2
workflows:
  version: 2
  server_and_web:
    jobs:
      - server
      - web
jobs:
  server:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo/server
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-server-{{ checksum "package-lock.json" }}
          - v1-dependencies-server-
      - run:
          name: Install NPM modules
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Compile
          command: npm run build
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test:ci
  web:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo/web
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-web-{{ checksum "package-lock.json" }}
          - v1-dependencies-web-
      - run:
          name: Install NPM modules
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Compile
          command: npm run build
      - run:
          name: Lint
          command: npm run lint
