type Mutation {
  createUser(username: String!, password: String!): User!
  createUserToken(username: String!, password: String!): String!
  reloadCampaigns(year: Int!): Boolean!
  reloadCongressMembers: Boolean!
  updateUserSettings(username: String, password: String): User!
}
