type MediaItem {
  id: Int!
  user: User!
  key: String!
  mimeType: String!
  createdAt: DateTime!

  token: String!
  # `data` is explicitly excluded because it's difficult/silly to send/stream binary over GQL.
  # `filename` is explicitly excluded because the client will never need it.
}
